version: '2'

services:
  scanomatic-frontend:
    image: phenomique/scanomatic:latest
    build: .
    ports: ["5000"]
    volumes:
      - scan-o-matic-home:/root/.scan-o-matic
      - somprojects:/somprojects
    environment:
      - SOM_BACKEND_HOST=scanomatic-backend
      - PGHOST=db
      - PGUSER=scanomatic
      - PGDATABASE=scanomatic

  scanomatic-backend:
    image: phenomique/scanomatic:latest
    build: .
    environment:
      - PGHOST=db
      - PGUSER=scanomatic
      - PGDATABASE=scanomatic
    volumes:
      - scan-o-matic-home:/root/.scan-o-matic
      - somprojects:/somprojects
    command: scan-o-matic_server

  db:
    image: postgres:10
    volumes:
      - "./scripts/setupdb.sh:/docker-entrypoint-initdb.d/setupdb.sh:ro"

volumes:
  scan-o-matic-home: {}
  somprojects: {}
