version: '2'

services:
  scanomatic-frontend:
    image: phenomique/scanomatic:latest
    build: .
    ports: ["5000"]
    volumes:
      - scan-o-matic-home:/root/.scan-o-matic
      - somprojects:/somprojects
    command: scan-o-matic --no-browser

  scanomatic-backend:
    image: phenomique/scanomatic:latest
    build: .
    volumes:
      - scan-o-matic-home:/root/.scan-o-matic
      - somprojects:/somprojects
    command: scan-o-matic_server

volumes:
  scan-o-matic-home: {}
  somprojects: {}
