#!/usr/bin/env python
"""Scan-o-Matic Server"""
__author__ = "Martin Zackrisson"
__copyright__ = "Swedish copyright laws apply"
__credits__ = ["Martin Zackrisson"]
__license__ = "GPL v3.0"
__version__ = "0.9991"
__maintainer__ = "Martin Zackrisson"
__email__ = "martin.zackrisson@gu.se"
__status__ = "Development"


#
# DEPENDENCIES
#

import psutil
import sys
import os
#
# INTERNAL DEPENDENCIES
#

import scanomatic.io.logger as logger
import scanomatic.rpc_server.server as server

if __name__ == "__main__":

    basename = os.path.basename(sys.argv[0])[:15]

    for p in psutil.get_process_list():

        try:

            if (p.name.startswith(basename) and
                    os.getpid() != p.pid):

                logger.Logger("Scan-o-Matic server launcher").critical(
                    "There is already a Scan-o-Matic server running, " +
                    "request refused!")
                sys.exit(9)

        except psutil.NoSuchProcess:

            pass

    rpcServer = server.SOM_RPC()
    rpcServer.run()
