#! /usr/bin/env python
from scanomatic.ui_server import ui_server
from argparse import ArgumentParser
import setproctitle
import sys

#
# EXECUTION BEHAVIOUR
#

if __name__ == "__main__":

    parser = ArgumentParser(description="""Scan-o-Matic""")

    parser.add_argument(
        "--port", type=int, dest="port", help="Manual override of default port")

    parser.add_argument(
        '--local', type=str, default="N", dest="local", help="Manual override if only to serve locally")

    parser.add_argument(
        '--host', type=str, dest="host", help="Manually setting host address of server")

    parser.add_argument(
        "--browser", type=str, dest="browser", default="Y", help="Open url to Scan-o-Matic in new tab (default True)"
    )

    parser.add_argument(
        "--debug", type=str, dest="debug", default="N", help="Run debug server (will crash and stuff on exceptions)" +
        " (default False)"
    )

    print(sys.argv)
    args = parser.parse_args()
    
    setproctitle.setproctitle("SoM {0}".format("UI Server"))
    true_strings = ['Y', 'YES', 'TRUE', 'T']
    ui_server.launch(open_browser_url=args.browser.upper() in true_strings,
                     debug=args.debug.upper() in true_strings,
                     is_local=args.local.upper() in true_strings, port=args.port, host=args.host)
