#!/usr/bin/env python

from argparse import ArgumentParser
from scanomatic.models.factories.compile_project_factory import CompileProjectFactory
import scanomatic.io.rpc_client as rpc_client

__author__ = 'martin'

if __name__ == "__main__":

    parser = ArgumentParser(
        description="""Runs Scan-o-Matic compile project\n\nNote: Will use all tiff images in path""")

    parser.add_argument(
        '-p', '--path', type=str, dest="path",
        help='Path to directory with files')

    parser.add_argument(
        '-f', '--fixture', type=str, dest='fixture',
        help="Fixture to use, it not supplied will use local fixture")

    args = parser.parse_args()

    client = rpc_client.get_client(admin=True)

    try:
        if client.create_compile_project_job(CompileProjectFactory.dict_from_path_and_fixture(args.path, args.fixture)):
            print "Job requested"
        else:
            print "Job refused"
    except AttributeError:
        print "Not enough privileges or server not running or bad arguments"
