#!/usr/bin/env python

from argparse import ArgumentParser
from scanomatic.io.first_pass_results import CompilationResults
from scanomatic.models.factories.analysis_factories import AnalysisModelFactory
import scanomatic.io.rpc_client as rpc_client

__author__ = 'martin'

if __name__ == "__main__":

    parser = ArgumentParser(description="""Runs Scan-o-Matic image analyses""")

    parser.add_argument(
        '-p', '--path', type=str, dest="path",
        help='Path to compilation file')

    parser.add_argument(
        '-i', '--instructions', type=str, dest='instructions',
        help='Path to compilation instructions if non-default'
    )

    args = parser.parse_args()

    analysis_model = AnalysisModelFactory.create(compilation=args.path,
                                                 compilation_instructions=args.instructions)

    if AnalysisModelFactory.validate(analysis_model):

        client = rpc_client.get_client(admin=True)
        try:
            client.create_analysis_job(analysis_model)
        except AttributeError:
            print "Not enough privileges or server not running"
        else:
            print "Job requested."
    else:
        print "Invalid arguments"