#!/usr/bin/env python
"""Scan-o-Matic"""
__author__ = "Martin Zackrisson"
__copyright__ = "Swedish copyright laws apply"
__credits__ = ["Martin Zackrisson"]
__license__ = "GPL v3.0"
__version__ = "0.9991"
__maintainer__ = "Martin Zackrisson"
__email__ = "martin.zackrisson@gu.se"
__status__ = "Development"


#
# DEPENDENCIES
#

from scanomatic.ui_server import ui_server
from argparse import ArgumentParser
import setproctitle

#
# EXECUTION BEHAVIOUR
#

if __name__ == "__main__":

    parser = ArgumentParser(description="""Scan-o-Matic""")

    parser.add_argument(
        "--port", type=int, dest="port", help="Manual override of default port")

    parser.add_argument(
        '--local', type=bool, dest="local", help="Manual override if only to serve locally")

    parser.add_argument(
        '--host', type=str, dest="host", help="Manually setting host address of server")

    parser.add_argument(
        "--browser", type=str, dest="browser", default="Y", help="Open url to Scan-o-Matic in new tab (default True)"
    )

    parser.add_argument(
        "--debug", type=str, dest="debug", default="N", help="Run debug server (will crash and stuff on exceptions)" +
        " (default False)"
    )

    args = parser.parse_args()
    
    setproctitle.setproctitle("SoM {0}".format("UI Server"))
    true_strings = ['Y', 'YES', 'TRUE', 'T']
    ui_server.launch(open_browser_url=args.browser.upper() in true_strings,
                     debug=args.debug.upper() in true_strings,
                     is_local=args.local, port=args.port, host=args.host)